spin_version = "1"
name = "hello-ruby-sinatra"
version = "0.1.3"
trigger = { type = "http", base = "/" }

[[component]]
id = "ruby-env"
source = "build/hello-ruby-sinatra.wasm"

[component.trigger]
executor = { type = "wagi", argv = "${SCRIPT_NAME} -v /lib/env.rb ${SCRIPT_NAME} ${ARGS}" }
route = "/env/..."

[component.environment]
HOME = "/"
GEM_HOME = "/.gem"

[[component]]
id = "sinatra-sample"
source = "build/hello-ruby-sinatra.wasm"

[component.trigger]
executor = { type = "wagi", argv = "${SCRIPT_NAME} -v /lib/sinatra_sample.rb ${SCRIPT_NAME} ${ARGS}" }
route = "/sinatra/..."

[component.environment]
HOME = "/"
GEM_HOME = "/.gem"
